### ISSUE TITLE
Unreadable text, wrong colours

### ISSUE THREAD

**Issue by pascalpuffke** [austinstanding/midnight-deep-vstheme#2]
Hey there,

I really have no idea what substances my installation of VS2022 has taken, but it really doesn't like custom colour schemes that much. It's probably not a problem directly related to your theme, as all the other themes seem to be broken too, I just have no idea where else to report it.

Standard VS themes obviously work just fine. Any ideas?

![Untitled](https://user-images.githubusercontent.com/30622888/124504652-335f1880-ddc8-11eb-9221-cbc8357ceb6b.png)

**Comment by austinstanding** [comment]
Thanks for bringing this up! I was able to replicate the issue using my theme in VS 2019. This isn't an issue with VS 2022, I'm afraid I simply never tested C++ with my themes. I suspect this is likely true of the other themes you have tried.

My themes are a personal project so I only see them in the workloads and features I use. I've installed the C++ workloads and I'll be working on C++ language support in my free time.

**Comment by austinstanding** [comment]
@pascalpuffke I found all of C++ was inheriting from the default theme, but it appeared to be the default light theme. The tokens you highlighted in your screenshot were simply black text. I've set all instances of black text in C++ to the default text color `#CCCCCC`, and brightened up keywords and enums for better visibility. bd9470a

I've already pushed the update the marketplace, all you need to do is update the extension to 1.2.3.

I'll likely revisit this in the future to introduce better differentiation in colorization, but for now I'm closing this issue. Thanks!
