### ISSUE TITLE
Texts in merge-window almost unreadable

### ISSUE THREAD

**Issue by WizX20** [austinstanding/midnight-deep-vstheme#3]
### Installed product versions
* Visual Studio: 2022 All Versions

### Description
The color-scheme for the merge-window makes text almost unreadable.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.
3. Start a merge conflict...

### Behavior
Example of .md file (same goes for .cs files):
![image](https://user-images.githubusercontent.com/1008647/139080141-f9ea34a5-708a-407d-a82e-b50bd634456a.png)

**Comment by austinstanding** [comment]
Thanks @WizX20 ! I must admit I don't use this feature much. I agree that's no good, see my updates in 0db311ded13f927cc67f098651ae93ea22bd1a0f and 7853cdc87129a64ce91d11c6d44b6c9075c88f4a . I thought the reds looked fine so I left those, however the conflict lines and also the Word Diffs needed some love. Here is a quick before/after I threw together with the changes.

![merge_conflict_contrast](https://user-images.githubusercontent.com/22038786/139516878-7a248e4e-794c-4ca6-b939-a68def74dc96.png)

I've already pushed these changes to the marketplace, you should be prompted to update to v1.2.5 next you open Visual Studio.

Thanks for helping improve the theme! ✌️
