### ISSUE TITLE
Resharper Font Issue

### ISSUE THREAD

**Issue by dean-dot-git** [austinstanding/midnight-deep-vstheme#4]
Is there any way you could add Resharper support please?    Here is what some of the inline stuff looks like and it is hard to read:

![image](https://user-images.githubusercontent.com/86485757/158812253-44606b18-2234-4dbc-94f1-de98387bb447.png)

Love your theme, anything you can do here would be awesome.

Thank you!

**Comment by austinstanding** [comment]
Hey @dean-dot-git , thanks for reaching out!

You could probably tell I haven't had ReSharper for a couple of years... I've installed it now but I seem to have a firewall blocking the final steps of activating the free trial. I was able to pull in the offending theme element but I can't run it to see for sure how it looks. 

Do you mind giving this update a run and sending me a new screenshot? Assuming it fixes the issue I'll deploy the update to the marketplace. (github apparently doesn't like .vsix files, you will have to unzip it first 🙄)

Glad you love the theme!

[MidnightDeep.vsix.zip](https://github.com/austinstanding/midnight-deep-vstheme/files/8310477/MidnightDeep.vsix.zip)

**Comment by austinstanding** [comment]
Hey @dean-dot-git how is it looking?

**Comment by dean-dot-git** [comment]
![image](https://user-images.githubusercontent.com/86485757/160755739-875ee2b7-aca4-4c93-ab14-4f858deb1ebf.png)

Significantly better!  That should do it.  Appreciate you taking a look and making this adjustment.  Let me know when the updated version is available offiically!

**Comment by austinstanding** [comment]
At this point @dean-dot-git, I'm going to need you to get your hands dirty for more info. Again, I can't run ReSharper to experiment, and unfortunately I'm not seeing any obvious names standing out like last time. I'm going to need you to create a variant theme to play with the values and get back to me:

- To start, download the [Visual Studio Color Theme Designer 2022](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022).

- Follow the steps it provides to create a new theme project, then when prompted to **Select a base theme**, choose **_MidnightDeep_** from the dropdown.

- Navigate to the **All elements** tab, and search for **_ReSharper_**.

- You can click an element's _Default_ value in the right column to change colors.

- Once you've changed a few and want to see what they look like, click the **Apply** button below to apply this variant theme. From there you can open a project to see your changes applied.

Please get back to me with the element names and maybe screenshots of the offending theme elements before/after a change. I'm not committing to take your color choices but with that info I can make further revisions.

> I recommend starting with the **_ReSharper Injected Language_** elements, as well as trying anything including **_hint_** or **_keyword_**.

What do you say?

**Comment by austinstanding** [comment]
Closing from inactivity. Feel free to reopen if you get that info!
